# ─── APP ───────────────────────────
spring.application.name=GrowIt
server.port=8080

# ─── DATABASE (MySQL) ─────────────
spring.datasource.url=jdbc:mysql://localhost:3306/growit_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=sherin611
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ─── JPA ──────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ─── THYMELEAF ────────────────────
spring.thymeleaf.cache=false