# ─── APP ───────────────────────────
spring.application.name=GrowIt
server.port=${PORT:8080}

# ─── DATABASE ─────────────────────
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA ──────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ─── THYMELEAF ────────────────────
spring.thymeleaf.cache=false