# ─── APP ───────────────────────────
spring.application.name=GrowIt
server.port=8080

# ─── DATABASE ─────────────────────
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/growit_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ─── JPA ──────────────────────────
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ─── THYMELEAF ────────────────────
spring.thymeleaf.cache=false